# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76fba34a5843e3cba3d97815814acbb7f358ae012fe09b5100978a905720f700e5d3c4abeb94bb522818618e9c0165248aa129e366e07dd8f5e32ca62c95a7ab

test:
  secret_key_base: 551cfc5e3ef716567c4becb6dbdc66e9018c4884d76f3591b860aa343d474304ca720cc841d53dcd2deff9cba064bf5fb31c04b0786696e4cfd786f99145d6c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
